name: Deploy Online Folder to Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:   # ←加上这一行，才会出现Run workflow手动按钮
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload online folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./online
      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v4